name: Docker Build and Push
on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
  
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: "danielvr91/dvr-test"
